name: windows-test
on: [push]

jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - run: echo "windows test"
      - uses: actions/checkout@v2
      - run: mvn -B clean install --file pom.xml
